version: "3"

services:
  app:
    build: .
    command: npm start

    ports:
      - "9000:3000"
    links:
      - db
    environment:
      SEQ_DB: api-vendas-db-1
      SEQ_USER: postgres
      SEQ_PW: docker
      PORT: 3000
      DATABASE_URL: postgres://postgres:docker@api-vendas-db-1:5432/api-vendas-db-1

    volumes:
      - .:/app
  db:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
